# Generated by Django 5.0.4 on 2024-05-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_author_remove_post_tags_project_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
