# Generated by Django 5.0.4 on 2024-05-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_feedback_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_email',
        ),
    ]
