# Generated by Django 5.0.4 on 2024-05-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_feedback_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
