# Generated by Django 5.0.4 on 2024-05-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_feedback_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='edit',
        ),
    ]
