# Generated by Django 5.0.4 on 2024-05-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_feedback_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
